### ISSUE TITLE
Doesn't support proxy

### ISSUE THREAD

**Issue by lonevvolf** [henriqb/ReCaptcha-Asp-Net#1]
Please provide a way to process the ValidateCaptcha call from behind a proxy.

**Comment by henriqb** [comment]
``` C#
private string GetClientIp()
{
    // Look for a proxy address first
    string ip = HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

    // If there is no proxy, get the standard remote address
    if (!string.IsNullOrWhiteSpace(ip) && ip.ToLower() != "unknown")
    {
        return ip;
    }
    return HttpContext.Current.Request.UserHostAddress;
}
```

Added a new function to WebPost class to check if it's being called from behind a proxy.
This should work.
v1.2.0 released. It's on Nuget.

**Comment by lonevvolf** [comment]
That isn't exactly what I meant, unfortunately.  I mean that the validation call from the web server to Google uses a WebRequest object which doesn't have an option to set a proxy (in case the web server or the development machine which needs to validate the response needs an outgoing proxy).

Though supporting the client IP is also useful.

**Comment by henriqb** [comment]
Hello @lonevvolf uploaded v1.3.0. Now it supports proxy calls.

It's on Nuget and here on Github.

```C#
...
const string proxyIp = "xxx.xxx.xxx.xxx";
const int proxyPort = 1234;
WebProxy webProxy = new WebProxy(proxyIp, proxyPort); 
bool validCaptcha = ReCaptcha.ValidateCaptcha(userResponse, webProxy);
...
```

Thanks for your help.
