### ISSUE TITLE
Specifying language explicitly does not work

### ISSUE THREAD

**Issue by igrm** [henriqb/ReCaptcha-Asp-Net#12]
Hello,
I need help with localization.
I am trying to show the reCaptcha in German with the following code:

![image](https://user-images.githubusercontent.com/24625265/50724199-4eb31500-10f2-11e9-8561-e2982538fd64.png)

reCaptcha is configured as follows:

![image](https://user-images.githubusercontent.com/24625265/50724204-67bbc600-10f2-11e9-97f0-a1df5819b9f9.png)

But it still is shown in English:

![image](https://user-images.githubusercontent.com/24625265/50724212-8cb03900-10f2-11e9-9a70-09a6404f4d24.png)

What am I doing wrong?

Thank you!

**Comment by henriqb** [comment]
Don't know if it works for me

![image](https://user-images.githubusercontent.com/8005448/50730851-60220e80-113e-11e9-9a76-a25b158cc95f.png)

It just adds this to the html html and js
`<div class="g-recaptcha" data-sitekey="your_site_key"></div><script src="https://www.google.com/recaptcha/api.js?**hl=de**"></script>
`
