### ISSUE TITLE
WebForms

### ISSUE THREAD

**Issue by NevillePerkins** [henriqb/ReCaptcha-Asp-Net#13]
Can this be implemented in WebForms? Not MVC or ASP Pages. For example I tried changing the client side script of
`@ReCaptcha.GetCaptcha()`
to
`<% ReCaptcha.GetCaptcha(); %>`
but no control is rendered.

**Comment by henriqb** [comment]
It works anywhere it just returns a string you need to put an equal
```<%= ReCaptcha.GetCaptcha() %>```
or 
```<% Response.Write(ReCaptcha.GetCaptcha()); %>```

**Comment by NevillePerkins** [comment]
This method also actually renders the ReCapthca control, right?
