### ISSUE TITLE
What is the correct @using statement?

### ISSUE THREAD

**Issue by phunkb** [henriqb/ReCaptcha-Asp-Net#15]
Using `@using hbehr.recaptcha` I just get that hbehr could not be found. Is this correct?

**Comment by henriqb** [comment]
It's 
```@using hbehr.recaptcha```

Maybe you are using the wrong .net Version.

**Comment by phunkb** [comment]
What is the required .net version for the package? Thanks.

**Comment by phunkb** [comment]
Ok, I think I am using 4.6. ` targeting '.NETFramework,Version=v4.6.1'`

Very strange

**Comment by phunkb** [comment]
Ok I have resolved the original issue, thank you. While im here if i could pick your brain, it only seems to go through and hit these breakpoints If I load the page, fill it in correctly, and submit the form: https://gyazo.com/76583fb24953a4591c89c9490f491935

If I load the page and incorrectly fill in the form, I receive validation warnings, but then it will never submit again?
