### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jerone** [henriqb/ReCaptcha-Asp-Net#16]
Hi, great package!

For me to update this package for our projects I need to know what changed. Right now that is not easy, because there is no changelog, no [release](https://github.com/henriqb/ReCaptcha-Asp-Net/releases) (or one really old) or no [tags](https://github.com/henriqb/ReCaptcha-Asp-Net/tags).

Would it be possible to define some changelog, or at least work with releases, so I and my team knows what changed between versions. Thanks.

**Comment by henriqb** [comment]
Can look on the nuget release notes

Release Notes
Added option to load on the dark theme
