### ISSUE TITLE
Current Version doesn't work with NewtonSoft.JSON 12

### ISSUE THREAD

**Issue by Saiyan** [henriqb/ReCaptcha-Asp-Net#18]
After upgrading the NewtonSoft.Json to version 12 in one of my projects the recaptcha package stopped working. Apparently it enforces the use of NewtonSoft.Json 9?

```
System.IO.FileLoadException: 'Could not load file or assembly "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Ausnahme von HRESULT: 0x80131040)'
```

**Comment by henriqb** [comment]
Thanks ! Much better now.

It's on nuget version 1.9.0

https://www.nuget.org/packages/ReCaptcha-AspNet/1.9.0
