### ISSUE TITLE
dependency on TLS 1.0/1?

### ISSUE THREAD

**Issue by lerickson-control4** [henriqb/ReCaptcha-Asp-Net#20]
I have an application using this library to do recaptcha verification, which works fine when running on a server where TLS 1.0, 1.1, and 1.2 are all enabled.  However when I run the app on a server on which only TLS 1.2 is enabled the verification step fails with a WebException inside this library.

My question: is there any chance that this component has some kind of hard dependency on TLS 1.0/1?  If so, I cannot use it in my target environment.  All my searches on this error point to a TLS rejection.

Here's the stack trace:
WebException exception-message="The underlying connection was closed: An unexpected error occurred on a receive." 
at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
at System.Net.HttpWebRequest.GetRequestStream()
at hbehr.recaptcha.WebCommunication.GoogleWebPost.CreatePostWebRequest(String postData, WebProxy proxy)
at hbehr.recaptcha.WebCommunication.GoogleWebPost.PostUserAnswer(String response, String secretKey, WebProxy proxy)
at hbehr.recaptcha.ReCaptchaObject.ValidateResponse(IReChaptaWebInterface webInterface, String response, WebProxy proxy)

**Comment by henriqb** [comment]
No, it's not on the code. Looks like a bug that MS introduced, on some W10 update.

You can fix by allowing TLS1.0 on server. Or do this, to force the .net to use TLS1.2 :

> Browse to the following registry key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NetFramework\v4.0.30319
>
> Right-click on the right pane and create a new DWORD (32-bit) Value with Name SchUseStrongCrypto.
>
> Ensure that the Value data field is set to 1 and the Base is Hexadecimal. Click on OK.
>
> Repeat steps 4 and 5 for the registry key: 
> HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319
> Restart the computer
