### ISSUE TITLE
Lower/remove newtonsoft.json requirement

### ISSUE THREAD

**Issue by Myster** [henriqb/ReCaptcha-Asp-Net#5]
Hi,
I'm wanting to add this to an old project, but because of the dependency chain starting at newtonsoft.json everything wants to upgrade

Is there a practical reason there could not be lower minimum version for newtonsoft.json?
(in my case 6.0.6 or less would be good)

**Comment by henriqb** [comment]
No practical reason. It will probably work with a lower Json version, It uses JSON.Net to deserialize the response from Google server validation.

**Comment by henriqb** [comment]
Lowered to 6.0.1 on 1.6.0
