### ISSUE TITLE
Image validation

### ISSUE THREAD

**Issue by KevinCocquyt39** [henriqb/ReCaptcha-Asp-Net#7]
Dear,

We implemented this easy to use library but we noticed an issue when applied for a certain customer of ours. Most of the time, a captcha appears where you have to check a box saying "I'm not a robot" and in that case, everything works fine... Only, from time to time, a captcha appears where you have to validate an image and as a result, the captcha could not be validated.

There is no such mention of this option so my question is, is there a possibility to support image validation? Or disable this option so it always results in the checkbox? Or is there a possibility within the Google Recaptcha website to do something about it?

Kind regards,
Kevin Cocquyt

**Comment by henriqb** [comment]
Please read how it works here, it will try to validate automatic the user, if it can't it will prompt a challenge:

https://www.google.com/recaptcha/intro/
